import type { Metadata } from 'next';
import './globals.css';
import SideBar from '@/components/SideBar';
import { locales } from '@/config';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export async function generateStaticParams() {
    return locales.map((lng) => ({ lng }));
}

export default function RootLayout({
    children,
    params: { lng },
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang={lng} className={'h-full'}>
            <body className={'h-full'}>
                <div className={'flex h-full'}>
                    <SideBar />
                    <section className={'m-6 flex-1 rounded bg-white p-10'}>{children}</section>
                </div>
            </body>
        </html>
    );
}
